using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Xml.Serialization;
using Barotrauma.LuaCs.Data;

namespace Barotrauma
{
	// Token: 0x020002F8 RID: 760
	[Obsolete("Use IModConfigInfo instead. This class exists for legacy compatibility only.")]
	[Serializable]
	public sealed class RunConfig : IRunConfig
	{
		// Token: 0x17001057 RID: 4183
		// (get) Token: 0x06003DE3 RID: 15843 RVA: 0x002316B8 File Offset: 0x0022F8B8
		// (set) Token: 0x06003DE4 RID: 15844 RVA: 0x002316C0 File Offset: 0x0022F8C0
		[XmlElement(ElementName = "Server")]
		[DefaultValue("Standard")]
		public string Server { get; set; }

		// Token: 0x17001058 RID: 4184
		// (get) Token: 0x06003DE5 RID: 15845 RVA: 0x002316C9 File Offset: 0x0022F8C9
		// (set) Token: 0x06003DE6 RID: 15846 RVA: 0x002316D1 File Offset: 0x0022F8D1
		[XmlElement(ElementName = "Client")]
		[DefaultValue("Standard")]
		public string Client { get; set; }

		// Token: 0x17001059 RID: 4185
		// (get) Token: 0x06003DE7 RID: 15847 RVA: 0x002316DA File Offset: 0x0022F8DA
		// (set) Token: 0x06003DE8 RID: 15848 RVA: 0x002316E2 File Offset: 0x0022F8E2
		[XmlArrayItem(ElementName = "Dependency", IsNullable = true, Type = typeof(RunConfig.Dependency))]
		[XmlArray]
		public RunConfig.Dependency[] Dependencies { get; set; }

		// Token: 0x1700105A RID: 4186
		// (get) Token: 0x06003DE9 RID: 15849 RVA: 0x002316EB File Offset: 0x0022F8EB
		// (set) Token: 0x06003DEA RID: 15850 RVA: 0x002316F3 File Offset: 0x0022F8F3
		[XmlElement(ElementName = "UseNonPublicizedAssemblies")]
		public bool UseNonPublicizedAssemblies { get; set; }

		// Token: 0x1700105B RID: 4187
		// (get) Token: 0x06003DEB RID: 15851 RVA: 0x002316FC File Offset: 0x0022F8FC
		// (set) Token: 0x06003DEC RID: 15852 RVA: 0x00231704 File Offset: 0x0022F904
		[XmlElement(ElementName = "UseInternalAssemblyName")]
		[DefaultValue(false)]
		public bool UseInternalAssemblyName { get; set; }

		// Token: 0x1700105C RID: 4188
		// (get) Token: 0x06003DED RID: 15853 RVA: 0x0023170D File Offset: 0x0022F90D
		// (set) Token: 0x06003DEE RID: 15854 RVA: 0x00231715 File Offset: 0x0022F915
		[XmlElement(ElementName = "AutoGenerated")]
		public bool AutoGenerated { get; set; }

		// Token: 0x06003DEF RID: 15855 RVA: 0x0023171E File Offset: 0x0022F91E
		public RunConfig(bool autoGenerated)
		{
			this.AutoGenerated = autoGenerated;
			if (autoGenerated)
			{
				this.Client = "Standard";
				this.Server = "Standard";
				this.UseNonPublicizedAssemblies = false;
			}
		}

		// Token: 0x06003DF0 RID: 15856 RVA: 0x0023174D File Offset: 0x0022F94D
		public RunConfig()
		{
		}

		// Token: 0x06003DF1 RID: 15857 RVA: 0x00231758 File Offset: 0x0022F958
		public RunConfig Sanitize()
		{
			try
			{
				this.Client = RunConfig.<Sanitize>g__SanitizeRunSetting|27_0(this.Client);
			}
			catch (Exception)
			{
				this.Client = "Standard";
			}
			try
			{
				this.Server = RunConfig.<Sanitize>g__SanitizeRunSetting|27_0(this.Server);
			}
			catch (Exception)
			{
				this.Server = "Standard";
			}
			if (this.Dependencies == null)
			{
				this.Dependencies = new RunConfig.Dependency[0];
			}
			return this;
		}

		// Token: 0x06003DF2 RID: 15858 RVA: 0x002317DC File Offset: 0x0022F9DC
		public bool IsForced()
		{
			return this.Client == "Forced";
		}

		// Token: 0x06003DF3 RID: 15859 RVA: 0x002317EE File Offset: 0x0022F9EE
		public bool IsStandard()
		{
			return this.Client == "Standard";
		}

		// Token: 0x06003DF4 RID: 15860 RVA: 0x00231800 File Offset: 0x0022FA00
		public bool IsForcedOrStandard()
		{
			return this.IsForced() || this.IsStandard();
		}

		// Token: 0x06003DF5 RID: 15861 RVA: 0x00231814 File Offset: 0x0022FA14
		[CompilerGenerated]
		internal static string <Sanitize>g__SanitizeRunSetting|27_0(string str)
		{
			string result;
			if (str != null)
			{
				if (str == null || str.Length != 0)
				{
					if (!(str == " "))
					{
						result = str[0].ToString().ToUpper() + str.Substring(1).ToLower();
					}
					else
					{
						result = "Standard";
					}
				}
				else
				{
					result = "Standard";
				}
			}
			else
			{
				result = "Standard";
			}
			return result;
		}

		// Token: 0x02000FA3 RID: 4003
		[Serializable]
		public sealed class Dependency
		{
			// Token: 0x04005635 RID: 22069
			[XmlElement(ElementName = "SteamWorkshopId")]
			public ulong SteamWorkshopId;

			// Token: 0x04005636 RID: 22070
			[XmlElement(ElementName = "PackageName")]
			public string PackageName;
		}
	}
}
