using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Xml.Serialization;
using Barotrauma.LuaCs.Data;

namespace Barotrauma
{
	// Token: 0x0200020F RID: 527
	[Obsolete("Use IModConfigInfo instead. This class exists for legacy compatibility only.")]
	[Serializable]
	public sealed class RunConfig : IRunConfig
	{
		// Token: 0x17000ABF RID: 2751
		// (get) Token: 0x0600250B RID: 9483 RVA: 0x000F422C File Offset: 0x000F242C
		// (set) Token: 0x0600250C RID: 9484 RVA: 0x000F4234 File Offset: 0x000F2434
		[XmlElement(ElementName = "Server")]
		[DefaultValue("Standard")]
		public string Server { get; set; }

		// Token: 0x17000AC0 RID: 2752
		// (get) Token: 0x0600250D RID: 9485 RVA: 0x000F423D File Offset: 0x000F243D
		// (set) Token: 0x0600250E RID: 9486 RVA: 0x000F4245 File Offset: 0x000F2445
		[XmlElement(ElementName = "Client")]
		[DefaultValue("Standard")]
		public string Client { get; set; }

		// Token: 0x17000AC1 RID: 2753
		// (get) Token: 0x0600250F RID: 9487 RVA: 0x000F424E File Offset: 0x000F244E
		// (set) Token: 0x06002510 RID: 9488 RVA: 0x000F4256 File Offset: 0x000F2456
		[XmlArrayItem(ElementName = "Dependency", IsNullable = true, Type = typeof(RunConfig.Dependency))]
		[XmlArray]
		public RunConfig.Dependency[] Dependencies { get; set; }

		// Token: 0x17000AC2 RID: 2754
		// (get) Token: 0x06002511 RID: 9489 RVA: 0x000F425F File Offset: 0x000F245F
		// (set) Token: 0x06002512 RID: 9490 RVA: 0x000F4267 File Offset: 0x000F2467
		[XmlElement(ElementName = "UseNonPublicizedAssemblies")]
		public bool UseNonPublicizedAssemblies { get; set; }

		// Token: 0x17000AC3 RID: 2755
		// (get) Token: 0x06002513 RID: 9491 RVA: 0x000F4270 File Offset: 0x000F2470
		// (set) Token: 0x06002514 RID: 9492 RVA: 0x000F4278 File Offset: 0x000F2478
		[XmlElement(ElementName = "UseInternalAssemblyName")]
		[DefaultValue(false)]
		public bool UseInternalAssemblyName { get; set; }

		// Token: 0x17000AC4 RID: 2756
		// (get) Token: 0x06002515 RID: 9493 RVA: 0x000F4281 File Offset: 0x000F2481
		// (set) Token: 0x06002516 RID: 9494 RVA: 0x000F4289 File Offset: 0x000F2489
		[XmlElement(ElementName = "AutoGenerated")]
		public bool AutoGenerated { get; set; }

		// Token: 0x06002517 RID: 9495 RVA: 0x000F4292 File Offset: 0x000F2492
		public RunConfig(bool autoGenerated)
		{
			this.AutoGenerated = autoGenerated;
			if (autoGenerated)
			{
				this.Client = "Standard";
				this.Server = "Standard";
				this.UseNonPublicizedAssemblies = false;
			}
		}

		// Token: 0x06002518 RID: 9496 RVA: 0x000F42C1 File Offset: 0x000F24C1
		public RunConfig()
		{
		}

		// Token: 0x06002519 RID: 9497 RVA: 0x000F42CC File Offset: 0x000F24CC
		public RunConfig Sanitize()
		{
			try
			{
				this.Client = RunConfig.<Sanitize>g__SanitizeRunSetting|27_0(this.Client);
			}
			catch (Exception)
			{
				this.Client = "Standard";
			}
			try
			{
				this.Server = RunConfig.<Sanitize>g__SanitizeRunSetting|27_0(this.Server);
			}
			catch (Exception)
			{
				this.Server = "Standard";
			}
			if (this.Dependencies == null)
			{
				this.Dependencies = new RunConfig.Dependency[0];
			}
			return this;
		}

		// Token: 0x0600251A RID: 9498 RVA: 0x000F4350 File Offset: 0x000F2550
		public bool IsForced()
		{
			return this.Server == "Forced";
		}

		// Token: 0x0600251B RID: 9499 RVA: 0x000F4362 File Offset: 0x000F2562
		public bool IsStandard()
		{
			return this.Server == "Standard";
		}

		// Token: 0x0600251C RID: 9500 RVA: 0x000F4374 File Offset: 0x000F2574
		public bool IsForcedOrStandard()
		{
			return this.IsForced() || this.IsStandard();
		}

		// Token: 0x0600251D RID: 9501 RVA: 0x000F4388 File Offset: 0x000F2588
		[CompilerGenerated]
		internal static string <Sanitize>g__SanitizeRunSetting|27_0(string str)
		{
			string result;
			if (str != null)
			{
				if (str == null || str.Length != 0)
				{
					if (!(str == " "))
					{
						result = str[0].ToString().ToUpper() + str.Substring(1).ToLower();
					}
					else
					{
						result = "Standard";
					}
				}
				else
				{
					result = "Standard";
				}
			}
			else
			{
				result = "Standard";
			}
			return result;
		}

		// Token: 0x020009D4 RID: 2516
		[Serializable]
		public sealed class Dependency
		{
			// Token: 0x04003474 RID: 13428
			[XmlElement(ElementName = "SteamWorkshopId")]
			public ulong SteamWorkshopId;

			// Token: 0x04003475 RID: 13429
			[XmlElement(ElementName = "PackageName")]
			public string PackageName;
		}
	}
}
