using System;

namespace Barotrauma.LuaCs.Data
{
	// Token: 0x02000476 RID: 1142
	public interface IRunConfig
	{
		// Token: 0x17001028 RID: 4136
		// (get) Token: 0x06003D83 RID: 15747
		bool UseNonPublicizedAssemblies { get; }

		// Token: 0x17001029 RID: 4137
		// (get) Token: 0x06003D84 RID: 15748
		bool AutoGenerated { get; }

		// Token: 0x1700102A RID: 4138
		// (get) Token: 0x06003D85 RID: 15749
		bool UseInternalAssemblyName { get; }

		// Token: 0x1700102B RID: 4139
		// (get) Token: 0x06003D86 RID: 15750
		string Client { get; }

		// Token: 0x1700102C RID: 4140
		// (get) Token: 0x06003D87 RID: 15751
		string Server { get; }

		// Token: 0x06003D88 RID: 15752
		bool IsForced();

		// Token: 0x06003D89 RID: 15753
		bool IsStandard();

		// Token: 0x06003D8A RID: 15754
		bool IsForcedOrStandard();
	}
}
