using System;

namespace Barotrauma.LuaCs.Data
{
	// Token: 0x02000593 RID: 1427
	public interface IRunConfig
	{
		// Token: 0x1700158D RID: 5517
		// (get) Token: 0x060056F2 RID: 22258
		bool UseNonPublicizedAssemblies { get; }

		// Token: 0x1700158E RID: 5518
		// (get) Token: 0x060056F3 RID: 22259
		bool AutoGenerated { get; }

		// Token: 0x1700158F RID: 5519
		// (get) Token: 0x060056F4 RID: 22260
		bool UseInternalAssemblyName { get; }

		// Token: 0x17001590 RID: 5520
		// (get) Token: 0x060056F5 RID: 22261
		string Client { get; }

		// Token: 0x17001591 RID: 5521
		// (get) Token: 0x060056F6 RID: 22262
		string Server { get; }

		// Token: 0x060056F7 RID: 22263
		bool IsForced();

		// Token: 0x060056F8 RID: 22264
		bool IsStandard();

		// Token: 0x060056F9 RID: 22265
		bool IsForcedOrStandard();
	}
}
